######################################################################
# Automatically generated by qmake (2.01a) gio dic 9 11:19:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/DrawManager.h src/RoomsEngine.h
SOURCES += src/DrawManager.cpp src/main.cpp src/RoomsEngine.cpp
